### PR TITLE
embed

### LINKED ISSUE #185: embed-video

### PR DESCRIPTION
**Pull request by 2016DigiTech**
Added embed you tube video at home page 

Fix #185 

Test URLs:https://embed--tlcgrp--hlxsites.hlx.page/

- Before: https://main--tlcgrp--hlxsites.hlx.page/
- After: https://embed--tlcgrp--hlxsites.hlx.page/

### CODE REVIEW

**Comment by 2016DigiTech** [comment]
@asthabh23 Please review #186 for YouTube embed video and also check lighthouse score. All css is according to styling format.

**Comment by asthabh23** [comment]
@2016DigiTech , The performance scores are impacted. please fix these

**Comment by 2016DigiTech** [comment]
> @2016DigiTech , The performance scores are impacted. please fix these

**Comment by 2016DigiTech** [comment]
> > @2016DigiTech , The performance scores are impacted. please fix these

@asthabh23 Yes, performance scores are impacted but i am not able to find out where we need to fix these.

**Comment by 2016DigiTech** [comment]
> > > @2016DigiTech , The performance scores are impacted. please fix these
> 
> @asthabh23 Yes, performance scores are impacted but i am not able to find out where we need to fix these. Please suggest.

**Pull request closed without merging**
