### PR TITLE
tech product code

### LINKED ISSUE #110: Google Tag Manager Integration on TLC Website.
Hi Team, 

Please add updated tag manager script as per the below script. 

Copy the code below and paste it onto every page of your website.
Paste this code as high in the <head> of the page as possible:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-W64FJ7M');</script>

Additionally, paste this code immediately after the opening <body> tag:

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W64FJ7M"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

### PR DESCRIPTION
**Pull request by 2016DigiTech**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #110

Test URLs:
- Before: https://main--tlcgrp--hlxsites.hlx.page/tech-products
- After: https://tech-product--tlcgrp--hlxsites.hlx.page/tech-products

### CODE REVIEW

**Comment by 2016DigiTech** [comment]
Hi Team 

Please review

**Review by asthabh23 — COMMENTED** [review]
Below, 900px there is a horizontal scrollbar that gets introduced, this might require a fix:
Screenshot 2023-02-13 at 1 58 03 PM

Also, below 600px, the hero image styling and content alignment is off as below:
Screenshot 2023-02-13 at 1 58 47 PM

In mobile view, cards have extra empty space towards the right:
Screenshot 2023-02-13 at 2 01 54 PM

**Comment by 2016DigiTech** [comment]
Hi Team, 

Please review PR

**Comment by asthabh23** [comment]
@2016DigiTech 
Between 600px and 1200px, the text alignment isn't right:
Screenshot 2023-02-13 at 3 27 35 PM

**Comment by 2016DigiTech** [comment]
Hi

Please Review

**Review by asthabh23 — APPROVED** [review]

**Pull request merged**
