### PR TITLE
footer styling

### LINKED ISSUE #182: Footer

### PR DESCRIPTION
**Pull request by 2016DigiTech**
Implement footer styling

Fix #182 

Test URLs: After: https://footer--tlcgrp--hlxsites.hlx.page/
Test URLs: After: https://footer--tlcgrp--hlxsites.hlx.page/clientele

- Before: https://main--tlcgrp--hlxsites.hlx.page/
- After: https://footer--tlcgrp--hlxsites.hlx.page/
- After: https://footer--tlcgrp--hlxsites.hlx.page/clientele

### CODE REVIEW

**Comment by 2016DigiTech** [comment]
@asthabh23 @vdua Please review #182

**Comment by asthabh23** [comment]
@2016DigiTech I see performance issues, please fix those on about-us page

**Comment by 2016DigiTech** [comment]
@asthabh23 please suggest how to fix from code side. 
image

**Comment by 2016DigiTech** [comment]
@asthabh23 Please review no need about page  changed in footer

**Review by asthabh23 — APPROVED** [review]

**Pull request merged**
